### ISSUE TITLE
walk_ratio

### ISSUE THREAD

**Issue by aremazeilles** [AdrianaTorres/Irregular_Terrains#6]
When launching it:

```
./run_pi_walk_ratio Walk_Ratio_octave/tests/data/input/GaitParameters_noExo.yaml output
current directory: /home/anthony/code/eurobench/csic/pi_irregular
gait yaml : Walk_Ratio_octave/tests/data/input/GaitParameters_noExo.yaml
result dir: output
filename = output/WalkingRatio.yaml
```
The result file contains:
```yaml
type: 'labelled_matrix'
Walking ratio:
[['right', 'left'], [NaN, NaN]]
```

We updated the output format, I would suggest using the vector format, with a label key, as you can see in the [doc](https://eurobench.github.io/sofware_documentation/latest/pi_spec.html#_output_data). 

Then, something might need to be revised, result being `NaN`.
