### ISSUE TITLE
ratio_index

### ISSUE THREAD

**Issue by aremazeilles** [AdrianaTorres/Irregular_Terrains#7]
```
./run_pi_ratio_index Ratio_Index_octave/tests/data/input/GaitParameters_noExo.yaml output
current directory: /home/anthony/code/eurobench/csic/pi_irregular
gait yaml : Ratio_Index_octave/tests/data/input/GaitParameters_noExo.yaml
result dir: output
filename = output/RatioIndex.yaml
```

It generates the file `output/RatioIndex.yaml`:

```yaml
type: 'labelled_matrix'
Ratio index:
[['cadence', 'walking_speed', 'stride_time', 'step_time', 'stride_length', 'step_length', 'step_width
', 'single_support'], [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN]]
```
Could you update the output format as mentioned in #6, and check if you are also having Nan score on your side?
